### PR TITLE
add SafePalWallet

### PR DESCRIPTION
**Pull request by bryanForSafe**
add SafePalWallet

### CODE REVIEW

**Comment by bryanForSafe** [comment]
bug

**Comment by tom-hippo** [comment]
Hello, could you point me to the official docs of safepal wallet? I don't really think it support Aptos ecosystem right now.

**Comment by bryanForSafe** [comment]
> 你好，你能指点我safepal钱包的官方文档吗？我真的不认为它现在支持 Aptos 生态系统。



> Hello, could you point me to the official docs of safepal wallet? I don't really think it support Aptos ecosystem right now.

Thank you. Aptos support in SafePal App will come in the next version, we will resubmit the PR after the new version lives.

**Comment by bryanForSafe** [comment]
> Hello, could you point me to the official docs of safepal wallet? I don't really think it support Aptos ecosystem right now.

Thank you. Aptos support in SafePal App will come in the next version, we will resubmit the PR after the new version lives.

**Comment by tom-hippo** [comment]
Thank you! Looking forward to it. Will close the PR for now.

**Pull request closed without merging**
