### PR TITLE
Support HyperPay Wallet Adapter

### PR DESCRIPTION
**Pull request by MacOMNI**
Apply for HyperPay Wallet Adapter

### CODE REVIEW

**Comment by tom-hippo** [comment]
Hi, thank you for the pr. Wonder if you can provide a develop doc of HyperPay wallet? I couldn't find it anywhere to have a review. Besides, I am not sure if HyperPay support Aptos ecosystem or not.

**Comment by MacOMNI** [comment]
Thank you for your reply. HyperPay mobile wallet already supports the aptos development network. The following is our link document about how to connect aptos dapp. I hope it can be helpful.

**Comment by MacOMNI** [comment]
The aptos dapp connection is currently in the test version. We will release this version after improving it with other functions.

**Comment by MacOMNI** [comment]
https://github.com/hyperpayorg/connect-dapps/blob/main/HowToConnectAptosDApp.md

**Comment by MacOMNI** [comment]
What is the current progress of hyperpay wallet adapter?

**Comment by MacOMNI** [comment]
> Hi, thank you for the pr. Wonder if you can provide a develop doc of HyperPay wallet? I couldn't find it anywhere to have a review. Besides, I am not sure if HyperPay support Aptos ecosystem or not.

What is the current progress of hyperpay wallet adapter?

**Pull request merged**
