### PR TITLE
feature: support aptos snap

### PR DESCRIPTION
**Pull request by zhaomengru2015**
## Add Aptos Snap

Aptos Snap is the application allowing users to directly manage Aptos within the MetaMask interface. Since Snaps is
pre-release software, the alpha version of Aptos Snap is currently live on [Metamask Flask](https://metamask.io/flask/), more details can be found [here](https://github.com/keystoneHQ/aptossnap).

### CODE REVIEW

**Comment by tom-hippo** [comment]
Hi @zhaomengru2015 , I am following the starting steps according to https://github.com/KeystoneHQ/aptossnap#how-to-start-testing-aptos-snap-alpha-version , however, there is no way to connect the new created wallet in metamask flask to https://keystonehq.github.io/aptossnap/ . 
The error returned:
{
    "code": 4100,
    "message": "Unauthorized to perform action. Try requesting the required permission(s) first. For more information, see: https://docs.metamask.io/guide/rpc-api.html#permissions",
    "data": {
        "origin": "https://keystonehq.github.io",
        "method": "wallet_snap_npm:@keystonehq/aptossnap"
    }
 Is there any missing steps such as network config required in metamask flask etc?

**Comment by zhaomengru2015** [comment]
@tom-hippo, since 'SLIP-10' have not been officially release in Metamask flask, you need to build the flask from source at this stage as we detailed [here](https://github.com/KeystoneHQ/aptossnap#known-issue), Metamask will release it in about two weeks, we've already built a [zip](https://drive.google.com/file/d/1pobkTKT7kthzJ-7tSJp3BMmCfx0KjNeN/view), you can use it directly for convenience.

**Comment by tom-hippo** [comment]
Thank you for pointing out. I have overlooked that section. 
The wallet connect successfully. However, when I try to transfer/send aptos, there is error of 

> Transaction: Error: {"message":"Invalid transaction: Type: Validation Code: INSUFFICIENT_BALANCE_FOR_TRANSACTION_FEE","error_code":"vm_error","vm_error_code":5}

**Comment by zhaomengru2015** [comment]
@tom-hippo hi from the error message, it means the  account you've connected does not have enough balance, please faucet some APTOS and have  a try.

**Comment by zhaomengru2015** [comment]
@tom-hippo hi have you tried with an account with enough balance to pay the fee, does it work?

**Comment by tom-hippo** [comment]
I had tried to faucet the account through our wallet tester. The faucet is successful however the return txn link seems to be invalid and since I can't find the current value in the wallet through Metamask flask, i still got the insufficient balance error.

**Comment by tom-hippo** [comment]
@zhaomengru2015 can you check if you can faucet correctly and merge the latest commit? thank you!

**Comment by zhaomengru2015** [comment]
hi @tom-hippo I've reproduced the `INSUFFICIENT_BALANCE_FOR_TRANSACTION_FEE` error as you mentioned previously, I guess it caused by the aptos sdk upgrade, let me fix it and also resolve the conflict

**Comment by amalia20220301** [comment]
@tom-hippo the `INSUFFICIENT_BALANCE_FOR_TRANSACTION_FEE ` was caused by the `aptos snap` didn't support `txOption` to set the `max_gas_amount`. it has been fixed, please have a try

**Comment by amalia20220301** [comment]
@tom-hippo the `INSUFFICIENT_BALANCE_FOR_TRANSACTION_FEE ` was caused by the `aptos snap` didn't support `txOption` to set the `max_gas_amount`. it has been fixed, please have a try.

transfer

**Comment by zhaomengru2015** [comment]
@tom-hippo the `INSUFFICIENT_BALANCE_FOR_TRANSACTION_FEE ` was caused by the `aptos snap` didn't support `txOption` to set the `max_gas_amount`. it has been fixed, please have a try.

transfer

**Comment by tom-hippo** [comment]
@zhaomengru2015 thanks for resolving the issue! I got the transaction successfully, nevertheless, wonder if snap return the correct txt link? it will be great if you can merge the latest from the main and resolve the conflicts so that I can merge it. Thank you!

**Comment by amalia20220301** [comment]
@tom-hippo thanks for reviewing, the conflicts has been resolved.

**Comment by zhaomengru2015** [comment]
@tom-hippo thanks for reviewing, the conflicts have been resolved.

**Comment by zhaomengru2015** [comment]
> nevertheless, wonder if snap return the correct txt link?

@tom-hippo I'm sorry which link do you mean specifically?

**Pull request merged**
